Pizzeria/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Pizzeria.data;
using Pizzeria.Models;
using System.Security.Claims;

namespace Pizzeria.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthenticationSchemeProvider _schemeProvider;

        public LoginController(ApplicationDbContext context, IAuthenticationSchemeProvider schemeProvider)
        {
            _db = context;
            _schemeProvider = schemeProvider;
        }
        //GET
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Utente utente)
        {
            Utente? user = _db.Utenti.SingleOrDefault(x => x.Username == utente.Username && x.Password == utente.Password);

            if (user == null)
            {
                TempData["error"] = "Non esiste questo account";
                return View();
            }

            if (user.Username == "admin" && user.Password == "admin")
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Role, user.Ruolo),
                    new Claim(ClaimTypes.NameIdentifier, user.IdUtente.ToString())
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties();

                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);
                TempData["success"] = "Sezione Admin";
                return RedirectToAction("Index", "Home");
            }
            else if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.NameIdentifier, user.IdUtente.ToString())

                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties();

                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);
                TempData["message"] = "Login effettuato";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "Password sbagliata";
            }

            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            TempData["message"] = "Logout effettuato";
            return RedirectToAction("Index", "Home");

        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([Bind("Username, Password")] Utente utente)
        {

            var user = _db.Utenti.SingleOrDefault(x => x.Username == utente.Username);
            if (user != null)
            {
                TempData["error"] = "Username già esistente";
                return View();
            }
            ModelState.Remove("Ordini");
            if (ModelState.IsValid)
                try
                {


                    _db.Utenti.Add(utente);

                    _db.SaveChanges();
                    TempData["message"] = "Cliente aggiunto con successo";
                    //ritorna a Home Index
                    return RedirectToAction("Index", "Home");
                }

                catch (Exception ex)
                {
                    TempData["error"] = "Errore nella creazione dell'account, riprovare";

                    System.Diagnostics.Debug.WriteLine("ERROREEE" + ex.Message);
                }
            return View(utente);
        }
    }
}

Pizzeria/Controllers/OrdineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pizzeria.data;
using Pizzeria.Models;
using System.Security.Claims;

namespace Pizzeria.Controllers
{
    public class OrdineController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdineController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ordines
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Ordini.Include(o => o.Utente);
            var userId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));


            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Ordines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordine = await _context.Ordini
                .Include(o => o.Utente)
                .FirstOrDefaultAsync(m => m.IdOrdine == id);
            if (ordine == null)
            {
                return NotFound();
            }

            return View(ordine);
        }

        // GET: Ordines/Create
        public IActionResult Create()
        {
            var carrelloSession = HttpContext.Session.GetString("carrelloList");

            if (string.IsNullOrEmpty(carrelloSession))
            {
                TempData["error"] = "Carrello vuoto";
                return RedirectToAction("MostraCarrello", "Articolo");
            }
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        // POST: Ordines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdOrdine,IdUtente,Indirizzo,IsConsegnato,Note,DataOrdine,PrezzoTotale")] Ordine ordine)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            if (userId == null)
            {
                return RedirectToAction("Login", "Login");
            }
            ordine.IdUtente = Convert.ToInt32(userId);
            ordine.DataOrdine = DateTime.Now;

            _context.Ordini.Add(ordine);
            await _context.SaveChangesAsync();


            var carrelloSession = HttpContext.Session.GetString("carrelloList");

            if (!string.IsNullOrEmpty(carrelloSession))
            {
                var carrello = JsonConvert.DeserializeObject<List<Carrello>>(carrelloSession);
                double prezzoTotale = 0;
                foreach (var item in carrello)
                {

                    var dettagliOrdine = new DettagliOrdine
                    {
                        IdOrdine = ordine.IdOrdine,
                        IdArticolo = item.Articolo.IdArticolo,
                        Quantita = item.Quantita,
                        PrezzoUnitario = item.Articolo.Prezzo
                    };
                    _context.DettagliOrdini.Add(dettagliOrdine);
                    prezzoTotale += item.Quantita * item.Articolo.Prezzo;


                }
                ordine.PrezzoTotale = prezzoTotale;
                await _context.SaveChangesAsync();
                HttpContext.Session.Remove("carrelloList");
                TempData["success"] = "Ordine effettuato con successo";
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Ordines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordine = await _context.Ordini.FindAsync(id);
            if (ordine == null)
            {
                return NotFound();
            }
            ViewData["IdUtente"] = new SelectList(_context.Utenti, "IdUtente", "Username", ordine.IdUtente);
            return View(ordine);
        }

        // POST: Ordines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdOrdine,IdUtente,Indirizzo,IsConsegnato,Note")] Ordine ordine)
        {
            if (id != ordine.IdOrdine)
            {
                return NotFound();
            }
            ModelState.Remove("DettagliOrdini");
            ModelState.Remove("Utente");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ordine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdineExists(ordine.IdOrdine))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUtente"] = new SelectList(_context.Utenti, "IdUtente", "Username", ordine.IdUtente);
            return View(ordine);
        }

        // GET: Ordines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordine = await _context.Ordini
                .Include(o => o.Utente)
                .FirstOrDefaultAsync(m => m.IdOrdine == id);
            if (ordine == null)
            {
                return NotFound();
            }

            return View(ordine);
        }

        // POST: Ordines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordine = await _context.Ordini.FindAsync(id);
            if (ordine != null)
            {
                _context.Ordini.Remove(ordine);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdineExists(int id)
        {
            return _context.Ordini.Any(e => e.IdOrdine == id);
        }

        public async Task<IActionResult> InConsegna()
        {
            var inConsegna = await _context.Ordini.Where(o => o.IsConsegnato == false).ToListAsync();
            return View(inConsegna);
        }
        [HttpPost]
        public async Task<IActionResult> Consegnato(int id)
        {
            try
            {
                var ordine = await _context.Ordini.FindAsync(id);

                if (ordine == null)
                {
                    return StatusCode(404, "Article not found");
                }
                ordine.IsConsegnato = true;
                _context.Update(ordine);
                await _context.SaveChangesAsync();
                return StatusCode(200, "Article updated");
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
    }
}

Pizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - La Pizzaiuola </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    <link rel="stylesheet" href="~/Pizzeria.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body  data-bs-theme="light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">La Pizzaiuola </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Articolo" asp-action="Create">Aggiungi Articolo</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Articolo" asp-action="MostraCarrello">Carrello</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Ordine" asp-action="Index">Ordini</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Ordine" asp-action="InConsegna">Controllo Consegne</a>
                                </li>
                            }
                               
                        }
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="RiepilogoOrdine" asp-action="Index">Storico Ordini</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Articolo" asp-action="MostraCarrello">Carrello</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Articolo" asp-action="Index">Lista Articoli</a>
                        </li>
</ul>
<div>

                        @{
                            
                            if (User.Identity.IsAuthenticated)
                            {
                                <p class="nav-item  me-auto">
                                    <a class="nav-link text-dark fw-bold" asp-controller="Login" asp-action="Logout">Logout</a>
                                </p>
                                
                            }
                            else
                            {
                                <p class="nav-item me-auto">
                                    <a class="nav-link text-dark fw-bold fs-5" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                </p>
                            }
                           
                        }
</div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_PartialView" />
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
</body>
</html>

Pizzeria/Views/Shared/_PartialView.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["message"]');
    </script>
}