Pizzeria/Controllers/ArticoloController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pizzeria.data;
using Pizzeria.Models;

namespace Pizzeria.Controllers
{
    public class ArticoloController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArticoloController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Articolo
        public async Task<IActionResult> Index()
        {
            return View(await _context.Articoli.ToListAsync());
        }

        // GET: Articolo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articolo = await _context.Articoli
                .FirstOrDefaultAsync(m => m.IdArticolo == id);
            if (articolo == null)
            {
                return NotFound();
            }

            return View(articolo);
        }

        // GET: Articolo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articolo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdArticolo,Nome,Immagine,Prezzo,TempoConsegna,Ingredienti")] Articolo articolo)
        {
            ModelState.Remove("DettagliOrdini");
            if (ModelState.IsValid)
            {
                _context.Add(articolo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(articolo);
        }

        // GET: Articolo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articolo = await _context.Articoli.FindAsync(id);
            if (articolo == null)
            {
                return NotFound();
            }
            return View(articolo);
        }

        // POST: Articolo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdArticolo,Nome,Immagine,Prezzo,TempoConsegna,Ingredienti")] Articolo articolo)
        {

            if (id != articolo.IdArticolo)
            {
                return NotFound();
            }
            ModelState.Remove("DettagliOrdini");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(articolo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticoloExists(articolo.IdArticolo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(articolo);
        }

        // GET: Articolo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articolo = await _context.Articoli
                .FirstOrDefaultAsync(m => m.IdArticolo == id);
            if (articolo == null)
            {
                return NotFound();
            }

            return View(articolo);
        }

        // POST: Articolo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articolo = await _context.Articoli.FindAsync(id);
            if (articolo != null)
            {
                _context.Articoli.Remove(articolo);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool ArticoloExists(int id)
        {
            return _context.Articoli.Any(e => e.IdArticolo == id);
        }

        public HttpContext GetHttpContext()
        {
            return HttpContext;
        }

        public void AggiungiAlCarrello(int id)
        {
            bool isExist = false;
            var articolo = _context.Articoli.Find(id);
            if (articolo != null)
            {
                var carrelloSession = HttpContext.Session.GetString("carrelloList");
                if (carrelloSession != null)
                {
                    List<Carrello> cart = JsonConvert.DeserializeObject<List<Carrello>>(carrelloSession);
                    foreach (var item in cart)
                    {
                        if (item.Articolo.IdArticolo == id)
                        {

                            isExist = true;
                            item.Quantita += 1;
                            HttpContext.Session.SetString("carrelloList", JsonConvert.SerializeObject(cart));
                        }

                    }
                }
                if (isExist == false)
                {
                    Carrello carrello = new Carrello();
                    carrello.Articolo = articolo;
                    carrello.Quantita = 1;
                    List<Carrello> carrelloList = new List<Carrello>();
                    if (!string.IsNullOrEmpty(carrelloSession))
                    {
                        carrelloList = JsonConvert.DeserializeObject<List<Carrello>>(carrelloSession);
                    }
                    carrelloList.Add(carrello);
                    HttpContext.Session.SetString("carrelloList", JsonConvert.SerializeObject(carrelloList));
                }


            }
        }

        public IActionResult MostraCarrello()
        {
            List<Carrello> carrelloList = new List<Carrello>();
            var carrelloSession = HttpContext.Session.GetString("carrelloList");
            if (!string.IsNullOrEmpty(carrelloSession))
            {
                carrelloList = JsonConvert.DeserializeObject<List<Carrello>>(carrelloSession);
            }
            return View(carrelloList);
        }

        public IActionResult RimuoviDalCarrello(int id)
        {
            var carrelloSession = HttpContext.Session.GetString("carrelloList");
            if (carrelloSession != null)
            {
                List<Carrello> cart = JsonConvert.DeserializeObject<List<Carrello>>(carrelloSession);
                foreach (var item in cart)
                {
                    if (item.Articolo.IdArticolo == id)
                    {
                        cart.Remove(item);
                        HttpContext.Session.SetString("carrelloList", JsonConvert.SerializeObject(cart));
                        TempData["message"] = "Articolo rimosso dal carrello";
                        return RedirectToAction(nameof(MostraCarrello));
                    }
                }
            }
            TempData["error"] = "Articolo non trovato";
            return RedirectToAction(nameof(MostraCarrello));
        }
    }
}

Pizzeria/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pizzeria.Models;
using System.Diagnostics;

namespace Pizzeria.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pizzeria/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-10">
        <div class="text-center">
            <h1 class="display-4">Benvenuto in Pizzeria</h1>
            <a type="button" class="btn btn-outline-dark mb-2" asp-controller="Articolo" asp-action="Index"> Ordina Subito <i class="fa-solid fa-pizza-slice"></i></a>
            <p>Ordina la tua pizza preferita</p>
            <div class=" p-2" id="hero">

            <img src="https://www.triesteprima.it/~media/horizontal-hi/63689161222273/forno-a-legna-2.jpg" alt="Hero" class="rounded-2" />
            </div>
        </div>
    </div>
        @if(User.IsInRole("Admin")){
    <div class="col-md-2 bg-secondary rounded-3 p-3">
            <h5> Totale Ordini evasi</h5>
            <input class="form-control" type="text" id="totaleOrdini" value="0" disabled>
            <button id="aggiorna" class="btn btn-primary w-100 my-2">Aggiorna</button>

            <h5> Totale Incasso di Oggi</h5>

            <input class="form-control" type="date" id="data" />
            <button id="aggiornaTotale" class="btn btn-primary w-100 my-2">Aggiorna</button>
            <h6 id="totaleIncasso"> </h6>
    </div>
        }
</div>

@section Scripts{
    <script>
        $(document).ready(function(){
            $("#aggiorna").click(function(){
                $.ajax({
                    url: "/SezioneAdmin/OrdiniEvasi",
                    type: "GET",
                    success: function(data){
                        $("#totaleOrdini").val(data);
                    }
                });
            });
        });

     

    </script>
    <script>

        $(document).ready(function () {
            

            $("#aggiornaTotale").click(function () {

                var date = $("#data").val();
                var year = date.toString().split('-')[0];
                var month = date.toString().split('-')[1];
                var day = date.toString().split('-')[2];

                $.ajax({
                    url: '/SezioneAdmin/TotaleIncassodiOggi?year=' + year + '&month=' + month + '&day=' + day,
                    type: "GET",
                    success: function (data) {
                        $("#totaleIncasso").html("Totale Incasso di Oggi: " + data + "€");
                    }
                });
            });
        });
    </script>
}